## Regresion Project

### Importing models and dataset

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
%matplotlib inline

In [2]:
df1 = pd.read_csv("state-wise-women1.csv") 
df1.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 15 columns):
 #   Column                                                   Non-Null Count  Dtype 
---  ------                                                   --------------  ----- 
 0   State                                                    37 non-null     object
 1   Cases pending investigation from previous year           37 non-null     int64 
 2   Cases reported during the
year                           37 non-null     int64 
 3   Total cases for investigation                            37 non-null     int64 
 4   No of cases withdrawn by the Govt during investigation   37 non-null     int64 
 5   Cases transferred to other Police Station or Magistrate  37 non-null     int64 
 6   Cases not investigated Under 157_1_b CRPC                37 non-null     int64 
 7   Cases Not Chargesheeted but final report Submitted       37 non-null     int64 
 8   Cases ended as final report false         

In [3]:
x = df1.iloc[:-1, 1:-1].values
y = df1.iloc[:-1, -1].values 

In [4]:
x[:5] 

array([[ 970,  994, 1964,    0,   10,    0,    7,   33,    3,    0,   43,
         937,  990],
       [  34,   92,  126,    0,    0,    0,   14,    1,    3,    0,   18,
          63,   81],
       [2981, 1779, 4760,    0,    6,    0,  449,    0,    0,    0,  449,
        1276, 1731],
       [ 861, 1008, 1869,    0,    0,    0,   33,   53,    7,    5,   98,
        1157, 1255],
       [ 210, 1626, 1836,    0,    0,    0,   15,    8,    0,    0,   23,
        1608, 1631]], dtype=int64)

### No need for Encoding and also it has no missing Data

### Spliting the Data into training set and test set

In [5]:
from sklearn.model_selection import train_test_split 
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=0)

In [6]:
xtrain[:5]

array([[ 323, 1655, 1978,    0,   41,    0,    4,   18,    6,    0,   28,
        1311, 1380],
       [  11,   30,   41,    0,    0,    0,    1,    0,    0,    0,    1,
          23,   24],
       [  72,  336,  408,    0,    0,    0,   58,   14,    0,    1,   73,
         263,  336],
       [   4,    6,   10,    0,    0,    0,    0,    0,    0,    0,    0,
           4,    4],
       [1053, 2155, 3208,    0,    5,    0,   27,    6,   25,    0,   58,
        2109, 2172]], dtype=int64)

### Feaure Scaling

In [7]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
xtrain = sc.fit_transform(xtrain) 
xtest = sc.transform(xtest) 

In [8]:
xtrain[:5] 

array([[-0.1846515 ,  0.28379985,  0.18173757, -0.22808578,  4.17692903,
        -0.2773501 , -0.32405205, -0.26168454, -0.13763909, -0.39343842,
        -0.32739154,  0.17767275,  0.10530486],
       [-0.83093173, -0.83536233, -0.90836625, -0.22808578, -0.50123148,
        -0.2773501 , -0.3593116 , -0.32166135, -0.55055637, -0.39343842,
        -0.4078035 , -0.84819821, -0.84869535],
       [-0.70457566, -0.62461548, -0.70182619, -0.22808578, -0.50123148,
        -0.2773501 ,  0.31061984, -0.27501272, -0.55055637, -0.17743301,
        -0.19337161, -0.65704213, -0.62919088],
       [-0.84543161, -0.85189149, -0.92581241, -0.22808578, -0.50123148,
        -0.2773501 , -0.37106479, -0.32166135, -0.55055637, -0.39343842,
        -0.41078172, -0.8633314 , -0.86276615],
       [ 1.32747854,  0.62815744,  0.8739563 , -0.22808578,  0.0692759 ,
        -0.2773501 , -0.05372884, -0.30166908,  1.16993228, -0.39343842,
        -0.23804492,  0.81326671,  0.66250852]])

### Training various ML Models over same training model.

In [9]:
from sklearn.linear_model import LinearRegression 
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor 
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

lrr = LinearRegression()
lrr.fit(xtrain, ytrain) 
lrpred = lrr.predict(xtest) 

knnr = KNeighborsRegressor() 
knnr.fit(xtrain, ytrain) 
knnpred = knnr.predict(xtest) 

dtr = DecisionTreeRegressor(random_state=0) 
dtr.fit(xtrain, ytrain) 
dtpred = dtr.predict(xtest)  

svr = SVR(kernel="rbf") 
svr.fit(xtrain, ytrain) 
svmpred = svr.predict(xtest) 

rfr = RandomForestRegressor(n_estimators=10, random_state=0) 
rfr.fit(xtrain, ytrain) 
rfpred = rfr.predict(xtest) 

### Evaluating Models

In [10]:
from sklearn.metrics import r2_score

# Logestic Regressor
r2_score(ytest, lrpred)

1.0

In [11]:
# K-NearestNeighbour 
r2_score(ytest, knnpred) 

0.33123457204726414

In [12]:
# Decision Tree Classifier 
r2_score(ytest, dtpred) 

-0.13353413963044058

In [13]:
# Support Vector Machines 
r2_score(ytest, svmpred) 

-0.1626151711157171

In [15]:
# Random Forest 
r2_score(ytest, rfpred) 

0.5462161782827804

## End of the Project